name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Nginx build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Stop and run nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop nginx-server || true
            docker rm nginx-server || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server
            
            mkdir -p /server/nginx-server/www/fuks.ru
            mkdir -p /server/nginx-server/www/blog-backend.fuks.ru
            mkdir -p /server/nginx-server/www/auth.fuks.ru
            mkdir -p /server/nginx-server/www/admin.fuks.ru
            mkdir -p /server/nginx-server/www/story.fuks.ru
            mkdir -p /server/nginx-server/www/docs.fuks.ru
            mkdir -p /server/nginx-server/www/esenin-family.ru
            mkdir -p /server/nginx-server/www/mail.fuks.ru

            docker run --name nginx-server \
            --rm -d \
            -v "/server/nginx-server/www":"/var/www" \
            -v "/server/nginx-server/letsencrypt":"/etc/letsencrypt" \
            --network="fuks-ru" \
            -p 443:443 -p 80:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server

  notification:
    name: Notification

    needs: [build, deploy]

    runs-on: ubuntu-latest

    if: always()

    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        env:
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *nginx-server*
            
            [build and deploy](${{ env.ACTION_URL }}) by *${{ github.actor }}*
            
            steps: build *${{ needs.build.result == 'success' && '✅' || '⛔️' }}* deploy *${{ needs.deploy.result == 'success' && '✅' || '⛔️' }}*