name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Nginx build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fuks-server-nginx:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Stop and run nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker container stop fuks-server-nginx
            docker rm fuks-server-nginx
            docker rmi fuks-server-nginx
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fuks-server-nginx

            docker run --name fuks-server-nginx \
            --rm -d \
            -v "/server/fuks-server/www":"/var/www" \
            -v "/server/fuks-server/letsencrypt":"/etc/letsencrypt" \
            --network="fuks-ru" \
            -p 443:443 -p 80:80 \
            difuks/fuks-server-nginx