name: Update ssl certs for all domains

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update certs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run --rm \
            -v "/server/nginx-server/letsencrypt/:/etc/letsencrypt" \
            -v "/server/nginx-server/var/logs/letsencrypt/:/var/log/letsencrypt/" \
            -v "/server/nginx-server/www/:/var/www/" \
            certbot/certbot renew \
            -n \
            --agree-tos \
            --webroot

  notification:
    name: Notification

    needs: update

    runs-on: ubuntu-latest

    if: always()

    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        env:
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *nginx-server*
            
            [update certs](${{ env.ACTION_URL }}) by *${{ github.actor }}*
            
            steps: update *${{ needs.update.result == 'success' && '✅' || '⛔️' }}